# -*- coding: utf-8 -*-
"""word_embeddings_Kavyasree_Nunna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ti_t61KQs1eVT2O8R-5HAHTcj0Hat_k8

*# Installations:*
"""

!pip install sentence-transformers

"""# **The process follows a three-step pipeline:Sentence Embeddings:**

* We use the all-MiniLM-L6-v2 model (a lightweight
Transformer) to map each sentence into a 384-dimensional vector space.In this space, sentences with similar meanings are mathematically positioned close to one another.
* **Cosine Similarity:** To find the "distance" between the user's query and our dataset, we calculate the cosine of the angle between their vectors. A score closer to 1.0 indicates high semantic similarity.
*  **Top-K Retrieval:** The system ranks all sentences based on their similarity scores and returns the top $k$ results.
"""

from sentence_transformers import SentenceTransformer, util
import torch
import pandas as pd

# 1. SETUP: Load a lightweight, high-performance model
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. DATASET: 50 Synthetic Sentences
corpus = [
    # AI & Robotics (Inspired by your research)
    "VL-Maps allow for semantic navigation in 3D environments.",
    "The 2D-to-3D reconstruction pipeline uses depth estimation.",
    "Computer vision models like YOLO are used for real-time object detection.",
    "Mobile robots require SLAM for accurate mapping.",
    "Agentic AI systems can autonomously plan complex tasks.",
    "Point cloud data is essential for spatial understanding.",
    "Neural Radiance Fields (NeRF) represent 3D scenes using deep learning.",
    "Reinforcement learning helps robots learn through trial and error.",
    "Gaussian Splatting is a new technique for real-time 3D rendering.",
    "Transformers have revolutionized natural language processing.",

    # Carnatic Music (Inspired by your certifications)
    "Mayamalavagowla is often the first Raga taught to beginners.",
    "The Adi Tala consists of eight beats in a specific cycle.",
    "Sarali Varisai are fundamental sequences for vocal exercise.",
    "A Melakarta Raga is a parent scale in the Carnatic system.",
    "The Gamaka provides the unique ornamentation in Indian classical music.",
    "Katcheris usually begin with a Varnam to set the tempo.",
    "The Tanpura provides the essential shruti drone for the performer.",
    "Mridangam is the primary percussion instrument in a concert.",
    "Raga Shankarabharanam corresponds to the major scale in Western music.",
    "Manodharma is the art of improvised singing in Carnatic tradition.",

    # General Tech & Campus Life
    "The library at BITS Pilani remains open until midnight.",
    "Students can access high-speed Wi-Fi across the campus.",
    "How do I register for the upcoming hackathon?",
    "The cafeteria serves a variety of vegetarian meals.",
    "Where is the Google Developer Group meeting taking place?",
    "Machine Learning electives are available in the third year.",
    "Internship opportunities are posted on the university portal.",
    "The gym is located near the student housing complex.",
    "What are the requirements for a minor in Robotics?",
    "Submission deadlines for the final project are approaching."
]

# Add more generic sentences to reach 50...
for i in range(20):
    corpus.append(f"Generic informational sentence number {i+1} for dataset scaling.")

# 3. EMBEDDING GENERATION
print("Encoding dataset... please wait.")
corpus_embeddings = model.encode(corpus, convert_to_tensor=True)

# 4. SEARCH FUNCTION
def get_top_k(query, k=5):
    query_embedding = model.encode(query, convert_to_tensor=True)
    # Compute cosine similarity
    cos_scores = util.cos_sim(query_embedding, corpus_embeddings)[0]
    # Find the top k results
    top_results = torch.topk(cos_scores, k=k)

    results = []
    for score, idx in zip(top_results[0], top_results[1]):
        results.append({
            "Score": round(float(score), 4),
            "Text": corpus[idx]
        })
    return results

# 5. EXECUTION: Testing 5 Example Queries
test_queries = [
    "How can I build a 3D map from 2D images?",
    "What is the best Raga for a beginner?",
    "Where can I find a place to exercise?",
    "Is there help for coding projects?",
    "How many beats in a standard music cycle?"
]

print("\n--- SIMILARITY RESULTS ---")
for q in test_queries:
    print(f"\nQuery: {q}")
    matches = get_top_k(q, k=3)
    for m in matches:
        print(f" -> [{m['Score']}] {m['Text']}")